
{$IFDEF LCLGTK}
  {$i uses2_lclext_gtk.inc}
{$ENDIF}

{$IFDEF LCLGTK2}  
  {$i uses2_lclext_gtk2.inc}
{$ENDIF}

{$IFDEF LCLCarbon}  
  {$i uses2_lclext_carbon.inc}  
{$ENDIF}

{$IFDEF LCLCocoa}  
  {$i uses2_lclext_cocoa.inc}  
{$ENDIF}

{$IFDEF LCLWin32}  
  {$i uses2_lclext_win32.inc} 
{$ENDIF}

{$IFDEF LCLQT}  
  {$i uses2_lclext_qt.inc} 
{$ENDIF}

{$IFDEF LCLWince}
  {$i uses2_lclext_wince.inc}
{$ENDIF}

