SEARCH_DIR("/usr/lib/x86_64-linux-gnu/")
SEARCH_DIR("/lib64/")
SEARCH_DIR("/usr/lib/gcc/x86_64-linux-gnu/4.9/32/")
SEARCH_DIR("/usr/lib/i386-linux-gnu/")
SEARCH_DIR("/usr/lib32/")
SEARCH_DIR("/home/reinier/.lazarus/lib/DateTimeCtrls/lib/x86_64-linux/gtk2/")
SEARCH_DIR("/home/reinier/.lazarus/lib/IDEIntf/units/x86_64-linux/gtk2/")
SEARCH_DIR("/home/reinier/.lazarus/lib/SynEdit/units/x86_64-linux/gtk2/")
SEARCH_DIR("/home/reinier/.lazarus/lib/LazControls/lib/x86_64-linux/gtk2/")
SEARCH_DIR("/home/reinier/.lazarus/lib/units/x86_64-linux/gtk2/")
SEARCH_DIR("/home/reinier/.lazarus/lib/LCLBase/units/x86_64-linux/")
SEARCH_DIR("/home/reinier/.lazarus/lib/LazUtils/lib/x86_64-linux/")
SEARCH_DIR("/home/reinier/.lazarus/lib/units/x86_64-linux/")
SEARCH_DIR("./")
SEARCH_DIR("/usr/lib/codetyphon/fpc/fpc32/units/x86_64-linux/rtl/")
SEARCH_DIR("/usr/lib/codetyphon/fpc/fpc32/units/x86_64-linux/fcl-sound/")
SEARCH_DIR("/usr/lib/codetyphon/fpc/fpc32/units/x86_64-linux/newt/")
SEARCH_DIR("/usr/lib/codetyphon/fpc/fpc32/units/x86_64-linux/ptc/")
SEARCH_DIR("/usr/lib/codetyphon/fpc/fpc32/units/x86_64-linux/paszlib/")
SEARCH_DIR("/usr/lib/codetyphon/fpc/fpc32/units/x86_64-linux/pcap/")
SEARCH_DIR("/usr/lib/codetyphon/fpc/fpc32/units/x86_64-linux/iconvenc/")
SEARCH_DIR("/usr/lib/codetyphon/fpc/fpc32/units/x86_64-linux/oracle/")
SEARCH_DIR("/usr/lib/codetyphon/fpc/fpc32/units/x86_64-linux/fcl-db/")
SEARCH_DIR("/usr/lib/codetyphon/fpc/fpc32/units/x86_64-linux/utmp/")
SEARCH_DIR("/usr/lib/codetyphon/fpc/fpc32/units/x86_64-linux/fcl-web/")
SEARCH_DIR("/usr/lib/codetyphon/fpc/fpc32/units/x86_64-linux/cairo/")
SEARCH_DIR("/usr/lib/codetyphon/fpc/fpc32/units/x86_64-linux/gmp/")
SEARCH_DIR("/usr/lib/codetyphon/fpc/fpc32/units/x86_64-linux/postgres/")
SEARCH_DIR("/usr/lib/codetyphon/fpc/fpc32/units/x86_64-linux/regexpr/")
SEARCH_DIR("/usr/lib/codetyphon/fpc/fpc32/units/x86_64-linux/hermes/")
SEARCH_DIR("/usr/lib/codetyphon/fpc/fpc32/units/x86_64-linux/a52/")
SEARCH_DIR("/usr/lib/codetyphon/fpc/fpc32/units/x86_64-linux/odbc/")
SEARCH_DIR("/usr/lib/codetyphon/fpc/fpc32/units/x86_64-linux/fppkg/")
SEARCH_DIR("/usr/lib/codetyphon/fpc/fpc32/units/x86_64-linux/fcl-registry/")
SEARCH_DIR("/usr/lib/codetyphon/fpc/fpc32/units/x86_64-linux/lua/")
SEARCH_DIR("/usr/lib/codetyphon/fpc/fpc32/units/x86_64-linux/fftw/")
SEARCH_DIR("/usr/lib/codetyphon/fpc/fpc32/units/x86_64-linux/libenet/")
SEARCH_DIR("/usr/lib/codetyphon/fpc/fpc32/units/x86_64-linux/bfd/")
SEARCH_DIR("/usr/lib/codetyphon/fpc/fpc32/units/x86_64-linux/fcl-stl/")
SEARCH_DIR("/usr/lib/codetyphon/fpc/fpc32/units/x86_64-linux/fv/")
SEARCH_DIR("/usr/lib/codetyphon/fpc/fpc32/units/x86_64-linux/fcl-sdo/")
SEARCH_DIR("/usr/lib/codetyphon/fpc/fpc32/units/x86_64-linux/imagemagick/")
SEARCH_DIR("/usr/lib/codetyphon/fpc/fpc32/units/x86_64-linux/fcl-json/")
SEARCH_DIR("/usr/lib/codetyphon/fpc/fpc32/units/x86_64-linux/numlib/")
SEARCH_DIR("/usr/lib/codetyphon/fpc/fpc32/units/x86_64-linux/tcl/")
SEARCH_DIR("/usr/lib/codetyphon/fpc/fpc32/units/x86_64-linux/xforms/")
SEARCH_DIR("/usr/lib/codetyphon/fpc/fpc32/units/x86_64-linux/rtl-console/")
SEARCH_DIR("/usr/lib/codetyphon/fpc/fpc32/units/x86_64-linux/syslog/")
SEARCH_DIR("/usr/lib/codetyphon/fpc/fpc32/units/x86_64-linux/libgd/")
SEARCH_DIR("/usr/lib/codetyphon/fpc/fpc32/units/x86_64-linux/libpng/")
SEARCH_DIR("/usr/lib/codetyphon/fpc/fpc32/units/x86_64-linux/modplug/")
SEARCH_DIR("/usr/lib/codetyphon/fpc/fpc32/units/x86_64-linux/rtl-generics/")
SEARCH_DIR("/usr/lib/codetyphon/fpc/fpc32/units/x86_64-linux/pastojs/")
SEARCH_DIR("/usr/lib/codetyphon/fpc/fpc32/units/x86_64-linux/fcl-js/")
SEARCH_DIR("/usr/lib/codetyphon/fpc/fpc32/units/x86_64-linux/dblib/")
SEARCH_DIR("/usr/lib/codetyphon/fpc/fpc32/units/x86_64-linux/svgalib/")
SEARCH_DIR("/usr/lib/codetyphon/fpc/fpc32/units/x86_64-linux/rtl-extra/")
SEARCH_DIR("/usr/lib/codetyphon/fpc/fpc32/units/x86_64-linux/mad/")
SEARCH_DIR("/usr/lib/codetyphon/fpc/fpc32/units/x86_64-linux/symbolic/")
SEARCH_DIR("/usr/lib/codetyphon/fpc/fpc32/units/x86_64-linux/opencl/")
SEARCH_DIR("/usr/lib/codetyphon/fpc/fpc32/units/x86_64-linux/gdbm/")
SEARCH_DIR("/usr/lib/codetyphon/fpc/fpc32/units/x86_64-linux/fcl-xml/")
SEARCH_DIR("/usr/lib/codetyphon/fpc/fpc32/units/x86_64-linux/pasjpeg/")
SEARCH_DIR("/usr/lib/codetyphon/fpc/fpc32/units/x86_64-linux/fcl-async/")
SEARCH_DIR("/usr/lib/codetyphon/fpc/fpc32/units/x86_64-linux/gtk2/")
SEARCH_DIR("/usr/lib/codetyphon/fpc/fpc32/units/x86_64-linux/aspell/")
SEARCH_DIR("/usr/lib/codetyphon/fpc/fpc32/units/x86_64-linux/proj4/")
SEARCH_DIR("/usr/lib/codetyphon/fpc/fpc32/units/x86_64-linux/x11/")
SEARCH_DIR("/usr/lib/codetyphon/fpc/fpc32/units/x86_64-linux/gnome1/")
SEARCH_DIR("/usr/lib/codetyphon/fpc/fpc32/units/x86_64-linux/googleapi/")
SEARCH_DIR("/usr/lib/codetyphon/fpc/fpc32/units/x86_64-linux/fpgtk/")
SEARCH_DIR("/usr/lib/codetyphon/fpc/fpc32/units/x86_64-linux/openssl/")
SEARCH_DIR("/usr/lib/codetyphon/fpc/fpc32/units/x86_64-linux/ggi/")
SEARCH_DIR("/usr/lib/codetyphon/fpc/fpc32/units/x86_64-linux/hash/")
SEARCH_DIR("/usr/lib/codetyphon/fpc/fpc32/units/x86_64-linux/libcurl/")
SEARCH_DIR("/usr/lib/codetyphon/fpc/fpc32/units/x86_64-linux/httpd22/")
SEARCH_DIR("/usr/lib/codetyphon/fpc/fpc32/units/x86_64-linux/sqlite/")
SEARCH_DIR("/usr/lib/codetyphon/fpc/fpc32/units/x86_64-linux/pxlib/")
SEARCH_DIR("/usr/lib/codetyphon/fpc/fpc32/units/x86_64-linux/ldap/")
SEARCH_DIR("/usr/lib/codetyphon/fpc/fpc32/units/x86_64-linux/httpd24/")
SEARCH_DIR("/usr/lib/codetyphon/fpc/fpc32/units/x86_64-linux/fcl-process/")
SEARCH_DIR("/usr/lib/codetyphon/fpc/fpc32/units/x86_64-linux/gtk1/")
SEARCH_DIR("/usr/lib/codetyphon/fpc/fpc32/units/x86_64-linux/cdrom/")
SEARCH_DIR("/usr/lib/codetyphon/fpc/fpc32/units/x86_64-linux/dts/")
SEARCH_DIR("/usr/lib/codetyphon/fpc/fpc32/units/x86_64-linux/rsvg/")
SEARCH_DIR("/usr/lib/codetyphon/fpc/fpc32/units/x86_64-linux/fpmkunit/")
SEARCH_DIR("/usr/lib/codetyphon/fpc/fpc32/units/x86_64-linux/fcl-image/")
SEARCH_DIR("/usr/lib/codetyphon/fpc/fpc32/units/x86_64-linux/zlib/")
SEARCH_DIR("/usr/lib/codetyphon/fpc/fpc32/units/x86_64-linux/libvlc/")
SEARCH_DIR("/usr/lib/codetyphon/fpc/fpc32/units/x86_64-linux/pthreads/")
SEARCH_DIR("/usr/lib/codetyphon/fpc/fpc32/units/x86_64-linux/fcl-res/")
SEARCH_DIR("/usr/lib/codetyphon/fpc/fpc32/units/x86_64-linux/libxml2/")
SEARCH_DIR("/usr/lib/codetyphon/fpc/fpc32/units/x86_64-linux/fcl-extra/")
SEARCH_DIR("/usr/lib/codetyphon/fpc/fpc32/units/x86_64-linux/dbus/")
SEARCH_DIR("/usr/lib/codetyphon/fpc/fpc32/units/x86_64-linux/imlib/")
SEARCH_DIR("/usr/lib/codetyphon/fpc/fpc32/units/x86_64-linux/opengles/")
SEARCH_DIR("/usr/lib/codetyphon/fpc/fpc32/units/x86_64-linux/openal/")
SEARCH_DIR("/usr/lib/codetyphon/fpc/fpc32/units/x86_64-linux/fcl-base/")
SEARCH_DIR("/usr/lib/codetyphon/fpc/fpc32/units/x86_64-linux/fcl-fpcunit/")
SEARCH_DIR("/usr/lib/codetyphon/fpc/fpc32/units/x86_64-linux/opengl/")
SEARCH_DIR("/usr/lib/codetyphon/fpc/fpc32/units/x86_64-linux/zorba/")
SEARCH_DIR("/usr/lib/codetyphon/fpc/fpc32/units/x86_64-linux/fcl-passrc/")
SEARCH_DIR("/usr/lib/codetyphon/fpc/fpc32/units/x86_64-linux/uuid/")
SEARCH_DIR("/usr/lib/codetyphon/fpc/fpc32/units/x86_64-linux/rtl-objpas/")
SEARCH_DIR("/usr/lib/codetyphon/fpc/fpc32/units/x86_64-linux/fcl-net/")
SEARCH_DIR("/usr/lib/codetyphon/fpc/fpc32/units/x86_64-linux/chm/")
SEARCH_DIR("/usr/lib/codetyphon/fpc/fpc32/units/x86_64-linux/ibase/")
SEARCH_DIR("/usr/lib/codetyphon/fpc/fpc32/units/x86_64-linux/mysql/")
SEARCH_DIR("/usr/lib/codetyphon/fpc/fpc32/units/x86_64-linux/oggvorbis/")
SEARCH_DIR("/usr/lib/codetyphon/fpc/fpc32/units/x86_64-linux/fastcgi/")
SEARCH_DIR("/usr/lib/codetyphon/fpc/fpc32/units/x86_64-linux/unzip/")
SEARCH_DIR("/usr/lib/codetyphon/fpc/fpc32/units/x86_64-linux/libsee/")
SEARCH_DIR("/usr/lib/codetyphon/fpc/fpc32/units/x86_64-linux/sdl/")
SEARCH_DIR("/usr/lib/codetyphon/fpc/fpc32/units/x86_64-linux/libtar/")
SEARCH_DIR("/usr/lib/codetyphon/fpc/fpc32/units/x86_64-linux/users/")
SEARCH_DIR("/usr/lib/codetyphon/fpc/fpc32/units/x86_64-linux/ncurses/")
SEARCH_DIR("/usr/lib/codetyphon/fpc/fpc32/units/x86_64-linux/")
SEARCH_DIR("/usr/lib/codetyphon/fpc/fpc32/bin/x86_64-linux/")
SEARCH_DIR("/usr/lib/codetyphon/fpc/fpc32/bin/i386-linux/")
SEARCH_DIR("/usr/lib/")
INPUT(
/usr/lib/codetyphon/fpc/fpc32/units/x86_64-linux/rtl/cprt0.o
/usr/lib/x86_64-linux-gnu/crti.o
/usr/lib/gcc/x86_64-linux-gnu/4.9/32/crtbeginS.o
/datos/reinier/temp/src/lib/x86_64-linux/awgg.o
/datos/reinier/temp/src/lib/x86_64-linux/awgg.or
/usr/lib/codetyphon/fpc/fpc32/units/x86_64-linux/rtl/system.o
/usr/lib/codetyphon/fpc/fpc32/units/x86_64-linux/rtl/fpintres.o
/usr/lib/codetyphon/fpc/fpc32/units/x86_64-linux/rtl/objpas.o
/usr/lib/codetyphon/fpc/fpc32/units/x86_64-linux/rtl/cthreads.o
/usr/lib/codetyphon/fpc/fpc32/units/x86_64-linux/rtl/cmem.o
/home/reinier/.lazarus/lib/units/x86_64-linux/gtk2/interfaces.o
/home/reinier/.lazarus/lib/LCLBase/units/x86_64-linux/forms.o
/home/reinier/.lazarus/lib/DateTimeCtrls/lib/x86_64-linux/gtk2/datetimectrls.o
/datos/reinier/temp/src/lib/x86_64-linux/fmain.o
/datos/reinier/temp/src/lib/x86_64-linux/fnewdown.o
/datos/reinier/temp/src/lib/x86_64-linux/fconfig.o
/datos/reinier/temp/src/lib/x86_64-linux/fabout.o
/datos/reinier/temp/src/lib/x86_64-linux/flang.o
/datos/reinier/temp/src/lib/x86_64-linux/fstrings.o
/datos/reinier/temp/src/lib/x86_64-linux/freplace.o
/datos/reinier/temp/src/lib/x86_64-linux/fsitegrabber.o
/datos/reinier/temp/src/lib/x86_64-linux/fadd.o
/datos/reinier/temp/src/lib/x86_64-linux/fnotification.o
/datos/reinier/temp/src/lib/x86_64-linux/fcopymove.o
/datos/reinier/temp/src/lib/x86_64-linux/fconfirm.o
/datos/reinier/temp/src/lib/x86_64-linux/un_lineinfo.o
/usr/lib/codetyphon/fpc/fpc32/units/x86_64-linux/rtl/baseunix.o
/usr/lib/codetyphon/fpc/fpc32/units/x86_64-linux/rtl/unix.o
/usr/lib/codetyphon/fpc/fpc32/units/x86_64-linux/rtl/unixtype.o
/usr/lib/codetyphon/fpc/fpc32/units/x86_64-linux/rtl/initc.o
/usr/lib/codetyphon/fpc/fpc32/units/x86_64-linux/rtl/dl.o
/usr/lib/codetyphon/fpc/fpc32/units/x86_64-linux/rtl/unixutil.o
/usr/lib/codetyphon/fpc/fpc32/units/x86_64-linux/rtl/ctypes.o
/usr/lib/codetyphon/fpc/fpc32/units/x86_64-linux/rtl/cwstring.o
/home/reinier/.lazarus/lib/LCLBase/units/x86_64-linux/interfacebase.o
/usr/lib/codetyphon/fpc/fpc32/units/x86_64-linux/rtl/dynlibs.o
/usr/lib/codetyphon/fpc/fpc32/units/x86_64-linux/rtl/unixcp.o
/usr/lib/codetyphon/fpc/fpc32/units/x86_64-linux/rtl/types.o
/usr/lib/codetyphon/fpc/fpc32/units/x86_64-linux/rtl/classes.o
/usr/lib/codetyphon/fpc/fpc32/units/x86_64-linux/rtl/sysutils.o
/usr/lib/codetyphon/fpc/fpc32/units/x86_64-linux/rtl/math.o
/home/reinier/.lazarus/lib/LCLBase/units/x86_64-linux/lclstrconsts.o
/home/reinier/.lazarus/lib/LCLBase/units/x86_64-linux/lcltype.o
/home/reinier/.lazarus/lib/LCLBase/units/x86_64-linux/lclproc.o
/home/reinier/.lazarus/lib/LCLBase/units/x86_64-linux/lmessages.o
/usr/lib/codetyphon/fpc/fpc32/units/x86_64-linux/fcl-image/fpimage.o
/home/reinier/.lazarus/lib/LCLBase/units/x86_64-linux/graphtype.o
/home/reinier/.lazarus/lib/LCLBase/units/x86_64-linux/graphmath.o
/home/reinier/.lazarus/lib/LCLBase/units/x86_64-linux/intfgraphics.o
/home/reinier/.lazarus/lib/LCLBase/units/x86_64-linux/themes.o
/usr/lib/codetyphon/fpc/fpc32/units/x86_64-linux/rtl/typinfo.o
/usr/lib/codetyphon/fpc/fpc32/units/x86_64-linux/rtl/rtlconsts.o
/usr/lib/codetyphon/fpc/fpc32/units/x86_64-linux/rtl/linux.o
/usr/lib/codetyphon/fpc/fpc32/units/x86_64-linux/rtl/errors.o
/usr/lib/codetyphon/fpc/fpc32/units/x86_64-linux/rtl/sysconst.o
/home/reinier/.lazarus/lib/LazUtils/lib/x86_64-linux/lazlogger.o
/home/reinier/.lazarus/lib/LazUtils/lib/x86_64-linux/fpcadds.o
/home/reinier/.lazarus/lib/LazUtils/lib/x86_64-linux/avglvltree.o
/home/reinier/.lazarus/lib/LazUtils/lib/x86_64-linux/fileutil.o
/home/reinier/.lazarus/lib/LCLBase/units/x86_64-linux/wsreferences.o
/home/reinier/.lazarus/lib/LazUtils/lib/x86_64-linux/lazmethodlist.o
/home/reinier/.lazarus/lib/LazUtils/lib/x86_64-linux/lazutf8.o
/home/reinier/.lazarus/lib/LazUtils/lib/x86_64-linux/lazutf8classes.o
/home/reinier/.lazarus/lib/LazUtils/lib/x86_64-linux/lazloggerbase.o
/home/reinier/.lazarus/lib/LazUtils/lib/x86_64-linux/lazclasses.o
/usr/lib/codetyphon/fpc/fpc32/units/x86_64-linux/fcl-base/gettext.o
/home/reinier/.lazarus/lib/LazUtils/lib/x86_64-linux/masks.o
/home/reinier/.lazarus/lib/LazUtils/lib/x86_64-linux/lazfileutils.o
/usr/lib/codetyphon/fpc/fpc32/units/x86_64-linux/fcl-base/contnrs.o
/home/reinier/.lazarus/lib/LazUtils/lib/x86_64-linux/lazutilsstrconsts.o
/usr/lib/codetyphon/fpc/fpc32/units/x86_64-linux/fcl-image/fpreadbmp.o
/usr/lib/codetyphon/fpc/fpc32/units/x86_64-linux/fcl-image/fpwritebmp.o
/usr/lib/codetyphon/fpc/fpc32/units/x86_64-linux/fcl-image/bmpcomn.o
/home/reinier/.lazarus/lib/LCLBase/units/x86_64-linux/lclversion.o
/usr/lib/codetyphon/fpc/fpc32/units/x86_64-linux/fcl-image/fpreadpng.o
/usr/lib/codetyphon/fpc/fpc32/units/x86_64-linux/fcl-image/fpwritepng.o
/usr/lib/codetyphon/fpc/fpc32/units/x86_64-linux/fcl-image/fpreadtiff.o
/usr/lib/codetyphon/fpc/fpc32/units/x86_64-linux/fcl-image/fpwritetiff.o
/usr/lib/codetyphon/fpc/fpc32/units/x86_64-linux/fcl-image/fptiffcmn.o
/home/reinier/.lazarus/lib/LCLBase/units/x86_64-linux/icnstypes.o
/usr/lib/codetyphon/fpc/fpc32/units/x86_64-linux/fcl-image/fpimgcmn.o
/usr/lib/codetyphon/fpc/fpc32/units/x86_64-linux/fcl-image/pngcomn.o
/usr/lib/codetyphon/fpc/fpc32/units/x86_64-linux/paszlib/zstream.o
/usr/lib/codetyphon/fpc/fpc32/units/x86_64-linux/paszlib/zbase.o
/usr/lib/codetyphon/fpc/fpc32/units/x86_64-linux/paszlib/gzio.o
/usr/lib/codetyphon/fpc/fpc32/units/x86_64-linux/hash/crc.o
/usr/lib/codetyphon/fpc/fpc32/units/x86_64-linux/paszlib/zdeflate.o
/usr/lib/codetyphon/fpc/fpc32/units/x86_64-linux/paszlib/zinflate.o
/usr/lib/codetyphon/fpc/fpc32/units/x86_64-linux/paszlib/trees.o
/usr/lib/codetyphon/fpc/fpc32/units/x86_64-linux/paszlib/adler.o
/usr/lib/codetyphon/fpc/fpc32/units/x86_64-linux/paszlib/infblock.o
/usr/lib/codetyphon/fpc/fpc32/units/x86_64-linux/paszlib/infutil.o
/usr/lib/codetyphon/fpc/fpc32/units/x86_64-linux/paszlib/infcodes.o
/usr/lib/codetyphon/fpc/fpc32/units/x86_64-linux/paszlib/inftrees.o
/usr/lib/codetyphon/fpc/fpc32/units/x86_64-linux/paszlib/inffast.o
/home/reinier/.lazarus/lib/LCLBase/units/x86_64-linux/graphics.o
/home/reinier/.lazarus/lib/LCLBase/units/x86_64-linux/lclintf.o
/usr/lib/codetyphon/fpc/fpc32/units/x86_64-linux/fcl-image/fpcanvas.o
/usr/lib/codetyphon/fpc/fpc32/units/x86_64-linux/fcl-image/fpreadpnm.o
/usr/lib/codetyphon/fpc/fpc32/units/x86_64-linux/fcl-image/fpwritepnm.o
/usr/lib/codetyphon/fpc/fpc32/units/x86_64-linux/fcl-image/fpreadjpeg.o
/usr/lib/codetyphon/fpc/fpc32/units/x86_64-linux/fcl-image/fpwritejpeg.o
/usr/lib/codetyphon/fpc/fpc32/units/x86_64-linux/fcl-image/fpreadgif.o
/home/reinier/.lazarus/lib/LCLBase/units/x86_64-linux/lresources.o
/home/reinier/.lazarus/lib/LCLBase/units/x86_64-linux/lclrescache.o
/usr/lib/codetyphon/fpc/fpc32/units/x86_64-linux/fcl-image/clipping.o
/usr/lib/codetyphon/fpc/fpc32/units/x86_64-linux/pasjpeg/jpeglib.o
/usr/lib/codetyphon/fpc/fpc32/units/x86_64-linux/pasjpeg/jdapimin.o
/usr/lib/codetyphon/fpc/fpc32/units/x86_64-linux/pasjpeg/jdatasrc.o
/usr/lib/codetyphon/fpc/fpc32/units/x86_64-linux/pasjpeg/jdapistd.o
/usr/lib/codetyphon/fpc/fpc32/units/x86_64-linux/pasjpeg/jmorecfg.o
/usr/lib/codetyphon/fpc/fpc32/units/x86_64-linux/pasjpeg/jdeferr.o
/usr/lib/codetyphon/fpc/fpc32/units/x86_64-linux/pasjpeg/jinclude.o
/usr/lib/codetyphon/fpc/fpc32/units/x86_64-linux/pasjpeg/jerror.o
/usr/lib/codetyphon/fpc/fpc32/units/x86_64-linux/pasjpeg/jmemmgr.o
/usr/lib/codetyphon/fpc/fpc32/units/x86_64-linux/pasjpeg/jdmarker.o
/usr/lib/codetyphon/fpc/fpc32/units/x86_64-linux/pasjpeg/jdinput.o
/usr/lib/codetyphon/fpc/fpc32/units/x86_64-linux/pasjpeg/jcomapi.o
/usr/lib/codetyphon/fpc/fpc32/units/x86_64-linux/pasjpeg/jutils.o
/usr/lib/codetyphon/fpc/fpc32/units/x86_64-linux/pasjpeg/jmemnobs.o
/usr/lib/codetyphon/fpc/fpc32/units/x86_64-linux/pasjpeg/jdmaster.o
/usr/lib/codetyphon/fpc/fpc32/units/x86_64-linux/pasjpeg/jdcolor.o
/usr/lib/codetyphon/fpc/fpc32/units/x86_64-linux/pasjpeg/jdsample.o
/usr/lib/codetyphon/fpc/fpc32/units/x86_64-linux/pasjpeg/jdpostct.o
/usr/lib/codetyphon/fpc/fpc32/units/x86_64-linux/pasjpeg/jddctmgr.o
/usr/lib/codetyphon/fpc/fpc32/units/x86_64-linux/pasjpeg/jdphuff.o
/usr/lib/codetyphon/fpc/fpc32/units/x86_64-linux/pasjpeg/jdhuff.o
/usr/lib/codetyphon/fpc/fpc32/units/x86_64-linux/pasjpeg/jdcoefct.o
/usr/lib/codetyphon/fpc/fpc32/units/x86_64-linux/pasjpeg/jdmainct.o
/usr/lib/codetyphon/fpc/fpc32/units/x86_64-linux/pasjpeg/jquant1.o
/usr/lib/codetyphon/fpc/fpc32/units/x86_64-linux/pasjpeg/jquant2.o
/usr/lib/codetyphon/fpc/fpc32/units/x86_64-linux/pasjpeg/jdmerge.o
/usr/lib/codetyphon/fpc/fpc32/units/x86_64-linux/pasjpeg/jdct.o
/usr/lib/codetyphon/fpc/fpc32/units/x86_64-linux/pasjpeg/jidctfst.o
/usr/lib/codetyphon/fpc/fpc32/units/x86_64-linux/pasjpeg/jidctint.o
/usr/lib/codetyphon/fpc/fpc32/units/x86_64-linux/pasjpeg/jidctflt.o
/usr/lib/codetyphon/fpc/fpc32/units/x86_64-linux/pasjpeg/jidctred.o
/usr/lib/codetyphon/fpc/fpc32/units/x86_64-linux/pasjpeg/jcapistd.o
/usr/lib/codetyphon/fpc/fpc32/units/x86_64-linux/pasjpeg/jcapimin.o
/usr/lib/codetyphon/fpc/fpc32/units/x86_64-linux/pasjpeg/jdatadst.o
/usr/lib/codetyphon/fpc/fpc32/units/x86_64-linux/pasjpeg/jcparam.o
/usr/lib/codetyphon/fpc/fpc32/units/x86_64-linux/pasjpeg/jcinit.o
/usr/lib/codetyphon/fpc/fpc32/units/x86_64-linux/pasjpeg/jcmarker.o
/usr/lib/codetyphon/fpc/fpc32/units/x86_64-linux/pasjpeg/jcphuff.o
/usr/lib/codetyphon/fpc/fpc32/units/x86_64-linux/pasjpeg/jchuff.o
/usr/lib/codetyphon/fpc/fpc32/units/x86_64-linux/pasjpeg/jcmaster.o
/usr/lib/codetyphon/fpc/fpc32/units/x86_64-linux/pasjpeg/jccolor.o
/usr/lib/codetyphon/fpc/fpc32/units/x86_64-linux/pasjpeg/jcsample.o
/usr/lib/codetyphon/fpc/fpc32/units/x86_64-linux/pasjpeg/jcprepct.o
/usr/lib/codetyphon/fpc/fpc32/units/x86_64-linux/pasjpeg/jcdctmgr.o
/usr/lib/codetyphon/fpc/fpc32/units/x86_64-linux/pasjpeg/jccoefct.o
/usr/lib/codetyphon/fpc/fpc32/units/x86_64-linux/pasjpeg/jcmainct.o
/usr/lib/codetyphon/fpc/fpc32/units/x86_64-linux/pasjpeg/jfdctint.o
/usr/lib/codetyphon/fpc/fpc32/units/x86_64-linux/pasjpeg/jfdctfst.o
/usr/lib/codetyphon/fpc/fpc32/units/x86_64-linux/pasjpeg/jfdctflt.o
/home/reinier/.lazarus/lib/LCLBase/units/x86_64-linux/dynqueue.o
/home/reinier/.lazarus/lib/LazUtils/lib/x86_64-linux/lazconfigstorage.o
/usr/lib/codetyphon/fpc/fpc32/units/x86_64-linux/fcl-base/syncobjs.o
/home/reinier/.lazarus/lib/LazUtils/lib/x86_64-linux/utf8process.o
/home/reinier/.lazarus/lib/LCLBase/units/x86_64-linux/maps.o
/home/reinier/.lazarus/lib/LazUtils/lib/x86_64-linux/lazutf8sysutils.o
/home/reinier/.lazarus/lib/LCLBase/units/x86_64-linux/tmschema.o
/usr/lib/codetyphon/fpc/fpc32/units/x86_64-linux/fcl-process/process.o
/usr/lib/codetyphon/fpc/fpc32/units/x86_64-linux/fcl-process/pipes.o
/usr/lib/codetyphon/fpc/fpc32/units/x86_64-linux/rtl/termio.o
/home/reinier/.lazarus/lib/units/x86_64-linux/gtk2/gtk2disableliboverlay.o
/home/reinier/.lazarus/lib/units/x86_64-linux/gtk2/gtk2int.o
/usr/lib/codetyphon/fpc/fpc32/units/x86_64-linux/x11/xlib.o
/usr/lib/codetyphon/fpc/fpc32/units/x86_64-linux/x11/x.o
/usr/lib/codetyphon/fpc/fpc32/units/x86_64-linux/gtk2/gdk2x.o
/usr/lib/codetyphon/fpc/fpc32/units/x86_64-linux/gtk2/gdk2pixbuf.o
/usr/lib/codetyphon/fpc/fpc32/units/x86_64-linux/gtk2/gtk2.o
/usr/lib/codetyphon/fpc/fpc32/units/x86_64-linux/gtk2/gdk2.o
/usr/lib/codetyphon/fpc/fpc32/units/x86_64-linux/gtk2/glib2.o
/usr/lib/codetyphon/fpc/fpc32/units/x86_64-linux/gtk2/pango.o
/home/reinier/.lazarus/lib/LCLBase/units/x86_64-linux/dialogs.o
/home/reinier/.lazarus/lib/LCLBase/units/x86_64-linux/controls.o
/home/reinier/.lazarus/lib/LCLBase/units/x86_64-linux/dynhasharray.o
/home/reinier/.lazarus/lib/LCLBase/units/x86_64-linux/menus.o
/home/reinier/.lazarus/lib/LCLBase/units/x86_64-linux/wslclclasses.o
/home/reinier/.lazarus/lib/LCLBase/units/x86_64-linux/buttons.o
/home/reinier/.lazarus/lib/LCLBase/units/x86_64-linux/stdctrls.o
/home/reinier/.lazarus/lib/LCLBase/units/x86_64-linux/checklst.o
/home/reinier/.lazarus/lib/LCLBase/units/x86_64-linux/comctrls.o
/home/reinier/.lazarus/lib/LCLBase/units/x86_64-linux/spin.o
/home/reinier/.lazarus/lib/LCLBase/units/x86_64-linux/extctrls.o
/home/reinier/.lazarus/lib/units/x86_64-linux/gtk2/gtk2winapiwindow.o
/home/reinier/.lazarus/lib/units/x86_64-linux/gtk2/gtk2globals.o
/home/reinier/.lazarus/lib/units/x86_64-linux/gtk2/gtk2proc.o
/home/reinier/.lazarus/lib/units/x86_64-linux/gtk2/gtk2def.o
/home/reinier/.lazarus/lib/units/x86_64-linux/gtk2/gtk2fontcache.o
/home/reinier/.lazarus/lib/units/x86_64-linux/gtk2/gtk2extra.o
/home/reinier/.lazarus/lib/units/x86_64-linux/gtk2/gtk2msgqueue.o
/usr/lib/codetyphon/fpc/fpc32/units/x86_64-linux/x11/xrender.o
/usr/lib/codetyphon/fpc/fpc32/units/x86_64-linux/cairo/cairo.o
/usr/lib/codetyphon/fpc/fpc32/units/x86_64-linux/gtk2/atk.o
/home/reinier/.lazarus/lib/LCLBase/units/x86_64-linux/buttonpanel.o
/home/reinier/.lazarus/lib/LCLBase/units/x86_64-linux/lclclasses.o
/home/reinier/.lazarus/lib/LCLBase/units/x86_64-linux/clipbrd.o
/home/reinier/.lazarus/lib/LCLBase/units/x86_64-linux/customtimer.o
/home/reinier/.lazarus/lib/LCLBase/units/x86_64-linux/actnlist.o
/usr/lib/codetyphon/fpc/fpc32/units/x86_64-linux/fcl-base/custapp.o
/home/reinier/.lazarus/lib/LCLBase/units/x86_64-linux/helpintfs.o
/home/reinier/.lazarus/lib/LCLBase/units/x86_64-linux/imglist.o
/home/reinier/.lazarus/lib/LCLBase/units/x86_64-linux/wsimglist.o
/home/reinier/.lazarus/lib/LCLBase/units/x86_64-linux/wsproc.o
/home/reinier/.lazarus/lib/LCLBase/units/x86_64-linux/wsfactory.o
/home/reinier/.lazarus/lib/LCLBase/units/x86_64-linux/propertystorage.o
/usr/lib/codetyphon/fpc/fpc32/units/x86_64-linux/fcl-base/rttiutils.o
/usr/lib/codetyphon/fpc/fpc32/units/x86_64-linux/rtl-objpas/strutils.o
/home/reinier/.lazarus/lib/LCLBase/units/x86_64-linux/wsmenus.o
/home/reinier/.lazarus/lib/LCLBase/units/x86_64-linux/wscontrols.o
/home/reinier/.lazarus/lib/LCLBase/units/x86_64-linux/wsforms.o
/home/reinier/.lazarus/lib/LCLBase/units/x86_64-linux/imagelistcache.o
/home/reinier/.lazarus/lib/LCLBase/units/x86_64-linux/extendedstrings.o
/home/reinier/.lazarus/lib/LCLBase/units/x86_64-linux/textstrings.o
/home/reinier/.lazarus/lib/LCLBase/units/x86_64-linux/wsstdctrls.o
/home/reinier/.lazarus/lib/LCLBase/units/x86_64-linux/wsbuttons.o
/home/reinier/.lazarus/lib/LCLBase/units/x86_64-linux/popupnotifier.o
/usr/lib/codetyphon/fpc/fpc32/units/x86_64-linux/rtl/fgl.o
/home/reinier/.lazarus/lib/LCLBase/units/x86_64-linux/wsextctrls.o
/home/reinier/.lazarus/lib/LCLBase/units/x86_64-linux/wsdialogs.o
/home/reinier/.lazarus/lib/LCLBase/units/x86_64-linux/wschecklst.o
/home/reinier/.lazarus/lib/LCLBase/units/x86_64-linux/toolwin.o
/home/reinier/.lazarus/lib/LCLBase/units/x86_64-linux/wscomctrls.o
/home/reinier/.lazarus/lib/LCLBase/units/x86_64-linux/wstoolwin.o
/home/reinier/.lazarus/lib/LCLBase/units/x86_64-linux/wsspin.o
/usr/lib/codetyphon/fpc/fpc32/units/x86_64-linux/gtk2/gtk2ext.o
/home/reinier/.lazarus/lib/LCLBase/units/x86_64-linux/extdlgs.o
/home/reinier/.lazarus/lib/units/x86_64-linux/gtk2/gtk2debug.o
/home/reinier/.lazarus/lib/LCLBase/units/x86_64-linux/lclmessageglue.o
/home/reinier/.lazarus/lib/LCLBase/units/x86_64-linux/calendar.o
/home/reinier/.lazarus/lib/LCLBase/units/x86_64-linux/wscalendar.o
/home/reinier/.lazarus/lib/LCLBase/units/x86_64-linux/wsextdlgs.o
/home/reinier/.lazarus/lib/LCLBase/units/x86_64-linux/lclmemmanager.o
/home/reinier/.lazarus/lib/LCLBase/units/x86_64-linux/messages.o
/home/reinier/.lazarus/lib/units/x86_64-linux/gtk2/gtk2wsprivate.o
/usr/lib/codetyphon/fpc/fpc32/units/x86_64-linux/fcl-base/uriparser.o
/home/reinier/.lazarus/lib/units/x86_64-linux/gtk2/gtk2wscontrols.o
/home/reinier/.lazarus/lib/LCLBase/units/x86_64-linux/lazlinkedlist.o
/home/reinier/.lazarus/lib/units/x86_64-linux/gtk2/gtk2wsfactory.o
/home/reinier/.lazarus/lib/units/x86_64-linux/gtk2/gtk2wsstdctrls.o
/home/reinier/.lazarus/lib/units/x86_64-linux/gtk2/gtk2wschecklst.o
/home/reinier/.lazarus/lib/units/x86_64-linux/gtk2/gtk2themes.o
/home/reinier/.lazarus/lib/LCLBase/units/x86_64-linux/grids.o
/home/reinier/.lazarus/lib/LCLBase/units/x86_64-linux/pairsplitter.o
/home/reinier/.lazarus/lib/LCLBase/units/x86_64-linux/dynamicarray.o
/home/reinier/.lazarus/lib/LCLBase/units/x86_64-linux/maskedit.o
/home/reinier/.lazarus/lib/LazUtils/lib/x86_64-linux/laz2_xmlcfg.o
/home/reinier/.lazarus/lib/LazUtils/lib/x86_64-linux/lazfilecache.o
/home/reinier/.lazarus/lib/LazUtils/lib/x86_64-linux/laz2_dom.o
/home/reinier/.lazarus/lib/LazUtils/lib/x86_64-linux/laz2_xmlread.o
/home/reinier/.lazarus/lib/LazUtils/lib/x86_64-linux/laz2_xmlwrite.o
/home/reinier/.lazarus/lib/LazUtils/lib/x86_64-linux/lazutilities.o
/home/reinier/.lazarus/lib/LazUtils/lib/x86_64-linux/lazdbglog.o
/usr/lib/codetyphon/fpc/fpc32/units/x86_64-linux/fcl-base/avl_tree.o
/home/reinier/.lazarus/lib/LazUtils/lib/x86_64-linux/laz2_xmlutils.o
/home/reinier/.lazarus/lib/LCLBase/units/x86_64-linux/wsgrids.o
/home/reinier/.lazarus/lib/LCLBase/units/x86_64-linux/wspairsplitter.o
/home/reinier/.lazarus/lib/units/x86_64-linux/gtk2/gtk2wsbuttons.o
/home/reinier/.lazarus/lib/units/x86_64-linux/gtk2/gtk2wscalendar.o
/home/reinier/.lazarus/lib/units/x86_64-linux/gtk2/gtk2wscomctrls.o
/home/reinier/.lazarus/lib/units/x86_64-linux/gtk2/gtk2wsdialogs.o
/home/reinier/.lazarus/lib/units/x86_64-linux/gtk2/gtk2wsextctrls.o
/home/reinier/.lazarus/lib/units/x86_64-linux/gtk2/gtk2wsextdlgs.o
/home/reinier/.lazarus/lib/units/x86_64-linux/gtk2/gtk2wsforms.o
/home/reinier/.lazarus/lib/units/x86_64-linux/gtk2/gtk2wsgrids.o
/home/reinier/.lazarus/lib/units/x86_64-linux/gtk2/gtk2wsimglist.o
/home/reinier/.lazarus/lib/units/x86_64-linux/gtk2/gtk2wsmenus.o
/home/reinier/.lazarus/lib/units/x86_64-linux/gtk2/gtk2wsspin.o
/home/reinier/.lazarus/lib/units/x86_64-linux/gtk2/gtk2wspairsplitter.o
/home/reinier/.lazarus/lib/units/x86_64-linux/gtk2/gtk2cellrenderer.o
/home/reinier/.lazarus/lib/units/x86_64-linux/gtk2/gtk2listviewtreemodel.o
/home/reinier/.lazarus/lib/DateTimeCtrls/lib/x86_64-linux/gtk2/datetimepicker.o
/home/reinier/.lazarus/lib/DateTimeCtrls/lib/x86_64-linux/gtk2/dbdatetimepicker.o
/home/reinier/.lazarus/lib/DateTimeCtrls/lib/x86_64-linux/gtk2/datetimepickerpropedit.o
/home/reinier/.lazarus/lib/DateTimeCtrls/lib/x86_64-linux/gtk2/datetimecontrolsreg.o
/home/reinier/.lazarus/lib/DateTimeCtrls/lib/x86_64-linux/gtk2/calcontrolwrapper.o
/home/reinier/.lazarus/lib/DateTimeCtrls/lib/x86_64-linux/gtk2/lclcalwrapper.o
/home/reinier/.lazarus/lib/units/x86_64-linux/lazaruspackageintf.o
/usr/lib/codetyphon/fpc/fpc32/units/x86_64-linux/rtl-extra/clocale.o
/usr/lib/codetyphon/fpc/fpc32/units/x86_64-linux/rtl-objpas/dateutils.o
/usr/lib/codetyphon/fpc/fpc32/units/x86_64-linux/fcl-db/db.o
/home/reinier/.lazarus/lib/LCLBase/units/x86_64-linux/dbctrls.o
/usr/lib/codetyphon/fpc/fpc32/units/x86_64-linux/rtl-objpas/variants.o
/usr/lib/codetyphon/fpc/fpc32/units/x86_64-linux/rtl-objpas/fmtbcd.o
/usr/lib/codetyphon/fpc/fpc32/units/x86_64-linux/fcl-base/maskutils.o
/usr/lib/codetyphon/fpc/fpc32/units/x86_64-linux/rtl-objpas/varutils.o
/usr/lib/codetyphon/fpc/fpc32/units/x86_64-linux/fcl-db/dbconst.o
/home/reinier/.lazarus/lib/IDEIntf/units/x86_64-linux/gtk2/componenteditors.o
/home/reinier/.lazarus/lib/IDEIntf/units/x86_64-linux/gtk2/propedits.o
/home/reinier/.lazarus/lib/IDEIntf/units/x86_64-linux/gtk2/lazstringgridedit.o
/home/reinier/.lazarus/lib/IDEIntf/units/x86_64-linux/gtk2/checklistboxeditordlg.o
/home/reinier/.lazarus/lib/IDEIntf/units/x86_64-linux/gtk2/checkgroupeditordlg.o
/home/reinier/.lazarus/lib/IDEIntf/units/x86_64-linux/gtk2/propeditutils.o
/home/reinier/.lazarus/lib/IDEIntf/units/x86_64-linux/gtk2/objinspstrconsts.o
/home/reinier/.lazarus/lib/LCLBase/units/x86_64-linux/arrow.o
/home/reinier/.lazarus/lib/LCLBase/units/x86_64-linux/industrialbase.o
/home/reinier/.lazarus/lib/IDEIntf/units/x86_64-linux/gtk2/ideimagesintf.o
/home/reinier/.lazarus/lib/LCLBase/units/x86_64-linux/stringhashlist.o
/home/reinier/.lazarus/lib/LCLBase/units/x86_64-linux/editbtn.o
/home/reinier/.lazarus/lib/LCLBase/units/x86_64-linux/valedit.o
/home/reinier/.lazarus/lib/LCLBase/units/x86_64-linux/filectrl.o
/home/reinier/.lazarus/lib/IDEIntf/units/x86_64-linux/gtk2/frmselectprops.o
/home/reinier/.lazarus/lib/IDEIntf/units/x86_64-linux/gtk2/stringspropeditdlg.o
/home/reinier/.lazarus/lib/IDEIntf/units/x86_64-linux/gtk2/keyvalpropeditdlg.o
/home/reinier/.lazarus/lib/IDEIntf/units/x86_64-linux/gtk2/collectionpropeditform.o
/home/reinier/.lazarus/lib/IDEIntf/units/x86_64-linux/gtk2/filefilterpropeditor.o
/home/reinier/.lazarus/lib/LCLBase/units/x86_64-linux/calendarpopup.o
/home/reinier/.lazarus/lib/LCLBase/units/x86_64-linux/shellctrls.o
/home/reinier/.lazarus/lib/IDEIntf/units/x86_64-linux/gtk2/idewindowintf.o
/home/reinier/.lazarus/lib/IDEIntf/units/x86_64-linux/gtk2/texttools.o
/home/reinier/.lazarus/lib/SynEdit/units/x86_64-linux/gtk2/synhighlighterunixshellscript.o
/home/reinier/.lazarus/lib/SynEdit/units/x86_64-linux/gtk2/synedit.o
/datos/reinier/temp/src/lib/x86_64-linux/uniqueinstance.o
/datos/reinier/temp/src/lib/x86_64-linux/versionitis.o
/usr/lib/codetyphon/fpc/fpc32/units/x86_64-linux/fcl-base/inifiles.o
/home/reinier/.lazarus/lib/LCLBase/units/x86_64-linux/lcltranslator.o
/home/reinier/.lazarus/lib/SynEdit/units/x86_64-linux/gtk2/synedittypes.o
/home/reinier/.lazarus/lib/SynEdit/units/x86_64-linux/gtk2/synedithighlighter.o
/usr/lib/codetyphon/fpc/fpc32/units/x86_64-linux/fcl-registry/registry.o
/home/reinier/.lazarus/lib/SynEdit/units/x86_64-linux/gtk2/synedittextbase.o
/usr/lib/codetyphon/fpc/fpc32/units/x86_64-linux/fcl-registry/xmlreg.o
/usr/lib/codetyphon/fpc/fpc32/units/x86_64-linux/fcl-xml/dom.o
/usr/lib/codetyphon/fpc/fpc32/units/x86_64-linux/fcl-xml/xmlread.o
/usr/lib/codetyphon/fpc/fpc32/units/x86_64-linux/fcl-xml/xmlwrite.o
/usr/lib/codetyphon/fpc/fpc32/units/x86_64-linux/fcl-xml/xmlutils.o
/usr/lib/codetyphon/fpc/fpc32/units/x86_64-linux/fcl-xml/dtdmodel.o
/usr/lib/codetyphon/fpc/fpc32/units/x86_64-linux/fcl-xml/xmlreader.o
/usr/lib/codetyphon/fpc/fpc32/units/x86_64-linux/fcl-xml/xmltextreader.o
/home/reinier/.lazarus/lib/SynEdit/units/x86_64-linux/gtk2/syneditmiscprocs.o
/home/reinier/.lazarus/lib/SynEdit/units/x86_64-linux/gtk2/syneditkeycmds.o
/home/reinier/.lazarus/lib/SynEdit/units/x86_64-linux/gtk2/syneditstrconst.o
/home/reinier/.lazarus/lib/SynEdit/units/x86_64-linux/gtk2/syneditsearch.o
/home/reinier/.lazarus/lib/SynEdit/units/x86_64-linux/gtk2/syneditmousecmds.o
/home/reinier/.lazarus/lib/SynEdit/units/x86_64-linux/gtk2/syneditpointclasses.o
/home/reinier/.lazarus/lib/SynEdit/units/x86_64-linux/gtk2/synbeautifier.o
/home/reinier/.lazarus/lib/SynEdit/units/x86_64-linux/gtk2/syneditmarks.o
/home/reinier/.lazarus/lib/SynEdit/units/x86_64-linux/gtk2/syneditmarkup.o
/home/reinier/.lazarus/lib/SynEdit/units/x86_64-linux/gtk2/syneditmarkuphighall.o
/home/reinier/.lazarus/lib/SynEdit/units/x86_64-linux/gtk2/syneditmarkupbracket.o
/home/reinier/.lazarus/lib/SynEdit/units/x86_64-linux/gtk2/syneditmarkupwordgroup.o
/home/reinier/.lazarus/lib/SynEdit/units/x86_64-linux/gtk2/syneditmarkupctrlmouselink.o
/home/reinier/.lazarus/lib/SynEdit/units/x86_64-linux/gtk2/syneditmarkupspecialline.o
/home/reinier/.lazarus/lib/SynEdit/units/x86_64-linux/gtk2/syneditmarkupselection.o
/home/reinier/.lazarus/lib/SynEdit/units/x86_64-linux/gtk2/syneditmarkupspecialchar.o
/home/reinier/.lazarus/lib/SynEdit/units/x86_64-linux/gtk2/lazsynedittext.o
/home/reinier/.lazarus/lib/SynEdit/units/x86_64-linux/gtk2/synedittextbuffer.o
/home/reinier/.lazarus/lib/SynEdit/units/x86_64-linux/gtk2/syneditlines.o
/home/reinier/.lazarus/lib/SynEdit/units/x86_64-linux/gtk2/synedittexttrimmer.o
/home/reinier/.lazarus/lib/SynEdit/units/x86_64-linux/gtk2/synedittexttabexpander.o
/home/reinier/.lazarus/lib/SynEdit/units/x86_64-linux/gtk2/synedittextdoublewidthchars.o
/home/reinier/.lazarus/lib/SynEdit/units/x86_64-linux/gtk2/syneditfoldedview.o
/home/reinier/.lazarus/lib/SynEdit/units/x86_64-linux/gtk2/syngutterbase.o
/home/reinier/.lazarus/lib/SynEdit/units/x86_64-linux/gtk2/syngutter.o
/home/reinier/.lazarus/lib/SynEdit/units/x86_64-linux/gtk2/synguttercodefolding.o
/home/reinier/.lazarus/lib/SynEdit/units/x86_64-linux/gtk2/syngutterchanges.o
/home/reinier/.lazarus/lib/SynEdit/units/x86_64-linux/gtk2/syngutterlinenumber.o
/home/reinier/.lazarus/lib/SynEdit/units/x86_64-linux/gtk2/synguttermarks.o
/home/reinier/.lazarus/lib/SynEdit/units/x86_64-linux/gtk2/syngutterlineoverview.o
/home/reinier/.lazarus/lib/SynEdit/units/x86_64-linux/gtk2/syneditmiscclasses.o
/home/reinier/.lazarus/lib/SynEdit/units/x86_64-linux/gtk2/lazsyntextarea.o
/home/reinier/.lazarus/lib/SynEdit/units/x86_64-linux/gtk2/syntextdrawer.o
/home/reinier/.lazarus/lib/SynEdit/units/x86_64-linux/gtk2/synedittextbidichars.o
/home/reinier/.lazarus/lib/LCLBase/units/x86_64-linux/stdactns.o
/home/reinier/.lazarus/lib/SynEdit/units/x86_64-linux/gtk2/synregexpr.o
/home/reinier/.lazarus/lib/SynEdit/units/x86_64-linux/gtk2/lazsyneditmousecmdstypes.o
/home/reinier/.lazarus/lib/SynEdit/units/x86_64-linux/gtk2/synhighlighterpas.o
/home/reinier/.lazarus/lib/SynEdit/units/x86_64-linux/gtk2/synedithighlighterfoldbase.o
/home/reinier/.lazarus/lib/LCLBase/units/x86_64-linux/graphutil.o
/usr/lib/codetyphon/fpc/fpc32/units/x86_64-linux/fcl-process/simpleipc.o
/datos/reinier/temp/src/lib/x86_64-linux/uniqueinstancebase.o
/home/reinier/.lazarus/lib/LCLBase/units/x86_64-linux/translations.o
/home/reinier/.lazarus/lib/LazUtils/lib/x86_64-linux/lconvencoding.o
/usr/lib/codetyphon/fpc/fpc32/units/x86_64-linux/fcl-json/jsonparser.o
/usr/lib/codetyphon/fpc/fpc32/units/x86_64-linux/fcl-json/fpjson.o
/usr/lib/codetyphon/fpc/fpc32/units/x86_64-linux/rtl/dos.o
/usr/lib/codetyphon/fpc/fpc32/units/x86_64-linux/rtl/strings.o
/usr/lib/codetyphon/fpc/fpc32/units/x86_64-linux/fcl-json/jsonscanner.o
/datos/reinier/temp/src/lib/x86_64-linux/un_xtrctdwrflnfo.o
)
INPUT(
-lpthread
-ldl
-lX11
-lgdk_pixbuf-2.0
-lgtk-x11-2.0
-lgdk-x11-2.0
-lgobject-2.0
-lglib-2.0
-lgthread-2.0
-lgmodule-2.0
-lpango-1.0
-lcairo
-latk-1.0
)
GROUP(
-lc
)
INPUT(
/usr/lib/gcc/x86_64-linux-gnu/4.9/32/crtendS.o
/usr/lib/x86_64-linux-gnu/crtn.o
)
SECTIONS
{
  .fpcdata           :
  {
    KEEP (*(.fpc .fpc.n_version .fpc.n_links))
  }
  .threadvar : { *(.threadvar .threadvar.* .gnu.linkonce.tv.*) }
}
INSERT AFTER .data;
